# Generated by Django 5.2.2 on 2025-06-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni_foto',
            field=models.ImageField(blank=True, null=True, upload_to='dni_fotos/'),
        ),
    ]
