# Generated by Django 5.2.2 on 2025-06-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_dni_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='dni_foto',
            new_name='dni_foto_frontal',
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni_foto_trasera',
            field=models.ImageField(blank=True, null=True, upload_to='dni_fotos/'),
        ),
    ]
