# Generated by Django 5.2.3 on 2025-06-21 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_dni_foto_usuario_dni_foto_frontal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='puntuacion',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='ResenaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='resenas/')),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.resena')),
            ],
        ),
    ]
