# Generated by Django 5.2.3 on 2025-06-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_resena_puntuacion_resenaimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resena',
            name='imagen',
        ),
    ]
