# Generated by Django 5.2.3 on 2025-06-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='mapa_src',
            field=models.TextField(blank=True, help_text='Pega aquí el src del iframe de Google Maps', verbose_name='Código src de Google Maps'),
        ),
    ]
