# Generated by Django 5.2.3 on 2025-06-29 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evento_mapa_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteResena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.resena')),
            ],
        ),
    ]
